### ISSUE TITLE
New Developer

### ISSUE THREAD

**Issue by GadgetAddict** [ra1028/Former#20]
I cannot even call myself a developer yet, b/c I'm still brand new... so please forgive me for this....
When I Run Former  and even Former Demo,  it builds but there's no Simulator or even a Storyboard that I can find... I thought I was going to be able to see examples.

Thank you!

**Comment by metabren** [comment]
When you fire up the demo project in Xcode, have you tried changing the build scheme?

![Choosing a build scheme](https://cloud.githubusercontent.com/assets/749593/14245432/613b5936-fab5-11e5-893e-0bacb806f3fd.png)

The demo project launches with it set to the framework rather than the demo app.

**Comment by GadgetAddict** [comment]
Thank you Brendan,

I’ve never seen that section of Xcode and it was defaulted to the Framework.  When changing it to the Former-Demo it worked perfectly.

Wow..

Thank you for helping and for showing me something new.

Michael

**Comment by metabren** [comment]
No problem, Michael.  Happy coding! :)

**Comment by ZacharyKhan** [comment]
Could we close this issue?

**Comment by GadgetAddict** [comment]
Who is this and what issue are you talking about ?

**Comment by metabren** [comment]
@GadgetAddict you asked a question about the "Former" iOS library through Github issues. You got an email from @ZacharyKhan because he commented on the issue, asking if someone (you?) could close this issue as it's been solved.

Hopefully this screenshot comes through in the email but your reply went straight onto the Github issue:

![screen shot 2017-11-29 at 1 15 56 pm](https://user-images.githubusercontent.com/749593/33351193-7af3bfd4-d507-11e7-963c-0b7e786352de.png)

So, could you please login to Github and close this issue? Thanks muchly 😊

**Comment by GadgetAddict** [comment]
Yes.  Close
