### ISSUE TITLE
Custom UIView is not drawing in the cell

### ISSUE THREAD

**Issue by hussainashraf4u** [ra1028/Former#93]
**I have an .xib having some labels and a CircularProgressBar view which is IBInspectable which is drawing fine in .xib but when I am loading the cell in former, labels are showing up properly but not the progress view, i tried with other ProgressView library from github having same issue**

**To Reproduce**
1. Add CircularProgressBar to the project and create a cell in .xib and put the CircularProgressBar in the cell design '...'
2. Create an instance of the row former and add the row former to the former section '....'
3. Run the app, the progress view does not show up

**Expected behavior**
The progress view should be visible in the cell like other UI components

**Platform**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS12.1

**Comment by ZacharyKhan** [comment]
Hi Hussain, 

This issue can be due to a number of things outside the scope of Former. Your issue is most likely an issue with drawing/rendering the control you are trying to use. 

Since you are trying to stitch together Former and CircularProgressBar, I believe it may require some trial and error on your end. I am closing this issue as it is not an issue directly related to Former.
